-- insert into table [mathematics] --
INSERT INTO mathematics VALUES (1, 'Mathematics 01');
INSERT INTO mathematics VALUES (2, 'Mathematics 02');
INSERT INTO mathematics VALUES (3, 'Mathematics 03');
INSERT INTO mathematics VALUES (4, 'Mathematics 04');
INSERT INTO mathematics VALUES (5, 'Mathematics 05');
INSERT INTO mathematics VALUES (6, 'Mathematics 06');
INSERT INTO mathematics VALUES (7, 'Mathematics 07');
INSERT INTO mathematics VALUES (8, 'Mathematics 08');
INSERT INTO mathematics VALUES (9, 'Mathematics 09');
INSERT INTO mathematics VALUES (10, 'Mathematics & Scientifics 01');
INSERT INTO mathematics VALUES (11, 'Mathematics & Scientifics 02');
INSERT INTO mathematics VALUES (12, 'Mathematics & Scientifics 03');
INSERT INTO mathematics VALUES (13, 'Mathematics & Physical 01');
INSERT INTO mathematics VALUES (14, 'Mathematics & Physical 02');
INSERT INTO mathematics VALUES (15, 'Mathematics & Physical 03');

-- insert into table [physical] --
INSERT INTO physical VALUES (16, 'Physical 01');
INSERT INTO physical VALUES (17, 'Physical 02');
INSERT INTO physical VALUES (18, 'Physical 03');
INSERT INTO physical VALUES (19, 'Physical 04');
INSERT INTO physical VALUES (20, 'Physical 05');
INSERT INTO physical VALUES (21, 'Physical 06');
INSERT INTO physical VALUES (22, 'Physical 07');
INSERT INTO physical VALUES (23, 'Physical 08');
INSERT INTO physical VALUES (24, 'Physical 09');
INSERT INTO physical VALUES (13, 'Mathematics & Physical 01');
INSERT INTO physical VALUES (14, 'Mathematics & Physical 02');
INSERT INTO physical VALUES (15, 'Mathematics & Physical 03');
INSERT INTO physical VALUES (25, 'Physical & Scientifics 01');
INSERT INTO physical VALUES (26, 'Physical & Scientifics 02');
INSERT INTO physical VALUES (27, 'Physical & Scientifics 03');

-- insert into table [scientific] --
INSERT INTO scientific VALUES (10, 'Mathematics & Scientifics 01');
INSERT INTO scientific VALUES (11, 'Mathematics & Scientifics 02');
INSERT INTO scientific VALUES (12, 'Mathematics & Scientifics 03');
INSERT INTO scientific VALUES (25, 'Physical & Scientifics 01');
INSERT INTO scientific VALUES (26, 'Physical & Scientifics 02');
INSERT INTO scientific VALUES (27, 'Physical & Scientifics 03');
INSERT INTO scientific VALUES (28, 'scientific 01');
INSERT INTO scientific VALUES (29, 'scientific 02');
INSERT INTO scientific VALUES (30, 'scientific 03');
INSERT INTO scientific VALUES (31, 'scientific 04');
INSERT INTO scientific VALUES (32, 'scientific 05');
INSERT INTO scientific VALUES (33, 'scientific 06');
INSERT INTO scientific VALUES (34, 'scientific 07');
INSERT INTO scientific VALUES (35, 'scientific 08');
INSERT INTO scientific VALUES (36, 'scientific 09');

-- insert into table [books] --
INSERT INTO books VALUES (1, 1, '2016-01-01', 'tnanh', FALSE);
INSERT INTO books VALUES (2, 1, '2016-02-01', 'tnanh', FALSE);
INSERT INTO books VALUES (3, 2, '2016-03-01', 'tnanh', FALSE);
INSERT INTO books VALUES (4, 2, '2016-04-01', 'tnanh', FALSE);
INSERT INTO books VALUES (5, 2, '2016-05-01', 'tnanh', FALSE);
INSERT INTO books VALUES (6, 2, '2016-06-01', 'tnanh', FALSE);
INSERT INTO books VALUES (7, 3, '2016-07-01', 'tnanh', FALSE);
INSERT INTO books VALUES (8, 3, '2016-08-01', 'tnanh', FALSE);
INSERT INTO books VALUES (9, 4, '2016-08-01', 'tnanh', FALSE);
INSERT INTO books VALUES (10, 4, '2016-09-01', 'tnanh', FALSE);
INSERT INTO books VALUES (11, 5, '2016-10-01', 'tnanh', FALSE);
INSERT INTO books VALUES (12, 5, '2016-10-01', 'tnanh', FALSE);
INSERT INTO books VALUES (13, 5, '2016-11-01', 'tnanh', FALSE);
INSERT INTO books VALUES (14, 5, '2016-11-01', 'tnanh', FALSE);
INSERT INTO books VALUES (15, 5, '2016-12-01', 'tnanh', FALSE);
INSERT INTO books VALUES (16, 6, '2016-12-01', 'tnanh', FALSE);
INSERT INTO books VALUES (17, 6, '2017-01-01', 'tnanh', FALSE);
INSERT INTO books VALUES (18, 6, '2017-01-01', 'tnanh', FALSE);
INSERT INTO books VALUES (19, 6, '2017-02-01', 'tnanh', FALSE);
INSERT INTO books VALUES (20, 7, '2017-02-01', 'tnanh', FALSE);
INSERT INTO books VALUES (21, 7, '2017-03-01', 'tnanh', FALSE);
INSERT INTO books VALUES (22, 7, '2017-03-01', 'tnanh', FALSE);
INSERT INTO books VALUES (23, 7, '2017-04-01', 'tnanh', FALSE);
INSERT INTO books VALUES (24, 8, '2017-04-01', 'tnanh', FALSE);
INSERT INTO books VALUES (25, 8, '2017-05-01', 'tnanh', FALSE);
INSERT INTO books VALUES (26, 9, '2017-05-01', 'tnanh', FALSE);
INSERT INTO books VALUES (27, 9, '2017-06-01', 'tnanh', FALSE);
INSERT INTO books VALUES (28, 9, '2017-06-01', 'tnanh', FALSE);
INSERT INTO books VALUES (29, 10, '2017-07-01', 'tnanh', FALSE);
INSERT INTO books VALUES (30, 10, '2017-07-01', 'tnanh', FALSE);
INSERT INTO books VALUES (31, 10, '2017-08-01', 'tnanh', FALSE);
INSERT INTO books VALUES (32, 10, '2017-08-01', 'tnanh', FALSE);
INSERT INTO books VALUES (33, 10, '2017-09-01', 'tnanh', FALSE);
INSERT INTO books VALUES (34, 10, '2017-09-01', 'tnanh', FALSE);
INSERT INTO books VALUES (35, 10, '2017-10-01', 'tnanh', FALSE);
INSERT INTO books VALUES (36, 10, '2017-10-01', 'tnanh', FALSE);

-- insert into table [sort_description] --
INSERT INTO sort_description VALUES (1, 'short content 01', FALSE);
INSERT INTO sort_description VALUES (2, 'short content 02', FALSE);
INSERT INTO sort_description VALUES (3, 'short content 03', FALSE);
INSERT INTO sort_description VALUES (4, 'short content 04', FALSE);
INSERT INTO sort_description VALUES (5, 'short content 05', FALSE);
INSERT INTO sort_description VALUES (6, 'short content 06', FALSE);
INSERT INTO sort_description VALUES (7, 'short content 07', FALSE);
INSERT INTO sort_description VALUES (8, 'short content 08', FALSE);
INSERT INTO sort_description VALUES (9, 'short content 09', FALSE);
INSERT INTO sort_description VALUES (10, 'short content 10', FALSE);
INSERT INTO sort_description VALUES (11, 'short content 11', FALSE);
INSERT INTO sort_description VALUES (12, 'short content 12', FALSE);
INSERT INTO sort_description VALUES (13, 'short content 13', FALSE);
INSERT INTO sort_description VALUES (14, 'short content 14', FALSE);
INSERT INTO sort_description VALUES (15, 'short content 15', FALSE);
INSERT INTO sort_description VALUES (16, 'short content 16', FALSE);
INSERT INTO sort_description VALUES (17, 'short content 17', FALSE);
INSERT INTO sort_description VALUES (18, 'short content 18', FALSE);
INSERT INTO sort_description VALUES (19, 'short content 19', FALSE);
INSERT INTO sort_description VALUES (20, 'short content 20', FALSE);
INSERT INTO sort_description VALUES (21, 'short content 21', FALSE);
INSERT INTO sort_description VALUES (22, 'short content 22', FALSE);
INSERT INTO sort_description VALUES (23, 'short content 23', FALSE);
INSERT INTO sort_description VALUES (24, 'short content 24', FALSE);
INSERT INTO sort_description VALUES (25, 'short content 25', FALSE);
INSERT INTO sort_description VALUES (26, 'short content 26', FALSE);
INSERT INTO sort_description VALUES (27, 'short content 27', FALSE);
INSERT INTO sort_description VALUES (28, 'short content 28', FALSE);
INSERT INTO sort_description VALUES (29, 'short content 29', FALSE);
INSERT INTO sort_description VALUES (30, 'short content 30', FALSE);
INSERT INTO sort_description VALUES (31, 'short content 31', FALSE);
INSERT INTO sort_description VALUES (32, 'short content 32', FALSE);
INSERT INTO sort_description VALUES (33, 'short content 33', FALSE);
INSERT INTO sort_description VALUES (34, 'short content 34', FALSE);
INSERT INTO sort_description VALUES (35, 'short content 35', FALSE);
INSERT INTO sort_description VALUES (36, 'short content 36', FALSE);